### PR TITLE
disabling top level cloning of demos,tools and documentation repositories since they now submodules of main

### PR DESCRIPTION
**Pull request by lyskov**

### CODE REVIEW

**Comment by weitzner** [comment]
Could this also be modified to clone the submodules, possibly with a prompt to select just those that are required to build or others?

**Comment by lyskov** [comment]
@weitzner that is certainly possibly but i am not sure if that is desirable: - i would rather have initial clone to be in the minimal state so no disk space is wasted.

**Comment by weitzner** [comment]
My thinking is that after running the clone script you should be ready to build without having to hit the network again. Otherwise, why not just clone the main repo directly (i.e. not using this script)?

**Comment by lyskov** [comment]
@weitzner i see your point! 

OK, lets init essential submodules then. Brian, since you original author of `get_rosetta.sh` script, - would you like to add call to https://github.com/RosettaCommons/main/blob/master/source/update_submodules.sh to the appropriate place? Thanks,

**Comment by lyskov** [comment]
@weitzner looks like you busy at the moment so i will merge this as-is and we can see how to add additional cloning later

**Comment by weitzner** [comment]
It may be a little more complicated than that if you want to initialize the hooks and all that, too.

**Pull request merged**
